export const browserCoreExamples = [
  "paleoclaw browser status",
  "paleoclaw browser start",
  "paleoclaw browser stop",
  "paleoclaw browser tabs",
  "paleoclaw browser open https://example.com",
  "paleoclaw browser focus abcd1234",
  "paleoclaw browser close abcd1234",
  "paleoclaw browser screenshot",
  "paleoclaw browser screenshot --full-page",
  "paleoclaw browser screenshot --ref 12",
  "paleoclaw browser snapshot",
  "paleoclaw browser snapshot --format aria --limit 200",
  "paleoclaw browser snapshot --efficient",
  "paleoclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "paleoclaw browser navigate https://example.com",
  "paleoclaw browser resize 1280 720",
  "paleoclaw browser click 12 --double",
  'paleoclaw browser type 23 "hello" --submit',
  "paleoclaw browser press Enter",
  "paleoclaw browser hover 44",
  "paleoclaw browser drag 10 11",
  "paleoclaw browser select 9 OptionA OptionB",
  "paleoclaw browser upload /tmp/paleoclaw/uploads/file.pdf",
  'paleoclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "paleoclaw browser dialog --accept",
  'paleoclaw browser wait --text "Done"',
  "paleoclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "paleoclaw browser console --level error",
  "paleoclaw browser pdf",
];
