#!/bin/bash
# Daily Log Generator - Markdown Report Generation Script
# Part of PaleoClaw Activity Monitoring System

set -e

# Configuration
LOG_DIR=${ACTIVITY_LOG_DIR:-"$HOME/paleoclaw-logs/activity"}
SCREENSHOT_DIR=${SCREEN_MONITOR_DIR:-"$HOME/paleoclaw-logs/screenshots"}
OUTPUT_DIR=${DAILY_LOG_OUTPUT_DIR:-"$HOME/paleoclaw-logs/daily-logs"}
DATE=${1:-$(date +%Y-%m-%d)}
ACTIVITY_LOG="$LOG_DIR/activity_${DATE}.jsonl"
OUTPUT_FILE="$OUTPUT_DIR/daily-log_${DATE}.md"

# Create output directory
mkdir -p "$OUTPUT_DIR"

# Check if activity log exists
if [ ! -f "$ACTIVITY_LOG" ]; then
    echo "No activity log found for $DATE"
    exit 1
fi

# Function to count screenshots
count_screenshots() {
    local screenshot_dir="$SCREENSHOT_DIR/$DATE"
    if [ -d "$screenshot_dir" ]; then
        find "$screenshot_dir" -name "*.png" | wc -l
    else
        echo "0"
    fi
}

# Function to get top applications
get_top_applications() {
    jq -r 'select(.type=="application_switch") | .data.application' "$ACTIVITY_LOG" | \
        sort | uniq -c | sort -rn | head -10 | \
        awk '{printf "| %s | %d |\n", $2, $1}'
}

# Function to get activity count by type
get_activity_counts() {
    local app_count=$(jq -r 'select(.type=="application_switch")' "$ACTIVITY_LOG" | wc -l)
    local file_count=$(jq -r 'select(.type=="file_access")' "$ACTIVITY_LOG" | wc -l)
    local cmd_count=$(jq -r 'select(.type=="command_execution")' "$ACTIVITY_LOG" | wc -l)
    
    echo "$app_count|$file_count|$cmd_count"
}

# Function to get time range
get_time_range() {
    local first=$(jq -r '.timestamp' "$ACTIVITY_LOG" | head -1 | cut -dT -f2 | cut -d. -f1)
    local last=$(jq -r '.timestamp' "$ACTIVITY_LOG" | tail -1 | cut -dT -f2 | cut -d. -f1)
    echo "$first - $last"
}

# Function to calculate productivity score
calculate_productivity_score() {
    # Simple heuristic: based on activity frequency
    local total_activities=$(wc -l < "$ACTIVITY_LOG")
    local app_switches=$(jq -r 'select(.type=="application_switch")' "$ACTIVITY_LOG" | wc -l)
    
    # More app switches = more distraction = lower score
    # Baseline: 100, reduce by app switch frequency
    local score=$((100 - (app_switches / 10)))
    
    # Ensure score is between 0-100
    if [ $score -lt 0 ]; then score=0; fi
    if [ $score -gt 100 ]; then score=100; fi
    
    echo $score
}

# Generate Markdown report
generate_report() {
    local screenshot_count=$(count_screenshots)
    local counts=$(get_activity_counts)
    local app_count=$(echo $counts | cut -d'|' -f1)
    local file_count=$(echo $counts | cut -d'|' -f2)
    local cmd_count=$(echo $counts | cut -d'|' -f3)
    local time_range=$(get_time_range)
    local productivity_score=$(calculate_productivity_score)
    
    cat > "$OUTPUT_FILE" << EOF
# Daily Activity Log

**Date**: $DATE  
**Time Range**: $time_range  
**Productivity Score**: $productivity_score/100 ⭐

---

## 📊 Summary

| Metric | Value |
|--------|-------|
| Application Switches | $app_count |
| Files Accessed | $file_count |
| Commands Executed | $cmd_count |
| Screenshots Captured | $screenshot_count |

---

## 📱 Top Applications

| Application | Count |
|-------------|-------|
$(get_top_applications)

---

## 📁 Recent File Activity

$(jq -r 'select(.type=="file_access") | "- **\(.data.file)** - \(.data.action) at \(.timestamp | split("T")[1] | split(".")[0])"' "$ACTIVITY_LOG" | tail -20)

---

## 💻 Recent Commands

\`\`\`bash
$(jq -r 'select(.type=="command_execution") | .data.command' "$ACTIVITY_LOG" | tail -20)
\`\`\`

---

## 📸 Screenshots

**Total**: $screenshot_count screenshots

**Location**: \`$SCREENSHOT_DIR/$DATE/\`

---

## 🎯 Productivity Analysis

### Activity Distribution

$(jq -r '.type' "$ACTIVITY_LOG" | sort | uniq -c | sort -rn | awk '{printf "- %s: %d\n", $2, $1}')

### Peak Activity Hours

$(jq -r '.timestamp | split("T")[1] | split(":")[0]' "$ACTIVITY_LOG" | sort | uniq -c | sort -rn | head -5 | awk '{printf "- %s:00 - %d activities\n", $2, $1}')

---

## 📝 Notes

- Activity log: \`$ACTIVITY_LOG\`
- Screenshots: \`$SCREENSHOT_DIR/$DATE/\`
- Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

---

*Generated by PaleoClaw Daily Log Generator*  
*"Ex Fossilo, Scientia" - From Fossils, Knowledge*
EOF

    echo "Daily log generated: $OUTPUT_FILE"
}

# Function to generate weekly report
generate_weekly_report() {
    local week_start=$(date -d "last monday" +%Y-%m-%d 2>/dev/null || date -v-mon +%Y-%m-%d)
    local week_end=$(date +%Y-%m-%d)
    local output_file="$OUTPUT_DIR/weekly-log_${week_start}_to_${week_end}.md"
    
    cat > "$output_file" << EOF
# Weekly Activity Report

**Week**: $week_start to $week_end  
**Generated**: $(date +"%Y-%m-%d %H:%M:%S")

---

## 📊 Weekly Summary

EOF

    # Aggregate data from all days in the week
    for i in {0..6}; do
        local day=$(date -d "$week_start +$i days" +%Y-%m-%d 2>/dev/null || date -v-${i}d -j -f "%Y-%m-%d" "$week_start" +%Y-%m-%d)
        local day_log="$LOG_DIR/activity_${day}.jsonl"
        
        if [ -f "$day_log" ]; then
            local day_name=$(date -d "$day" +%A 2>/dev/null || date -j -f "%Y-%m-%d" "$day" +%A)
            local activity_count=$(wc -l < "$day_log")
            echo "- **$day_name ($day)**: $activity_count activities" >> "$output_file"
        fi
    done
    
    cat >> "$output_file" << EOF

---

*Generated by PaleoClaw Daily Log Generator*
EOF

    echo "Weekly report generated: $output_file"
}

# Main
case "${1:-today}" in
    today)
        DATE=$(date +%Y-%m-%d)
        generate_report
        ;;
    weekly)
        generate_weekly_report
        ;;
    *)
        # Treat as date
        if [[ "$1" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then
            DATE=$1
            generate_report
        else
            echo "Usage: $0 [today|weekly|YYYY-MM-DD]"
            echo "  today   - Generate report for today (default)"
            echo "  weekly  - Generate weekly report"
            echo "  YYYY-MM-DD - Generate report for specific date"
            exit 1
        fi
        ;;
esac
